# Generated by Django 5.0.6 on 2024-05-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BottomNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subname', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('dela', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MiniNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=128)),
                ('date', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=200)),
                ('dela', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('head', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('dela', models.CharField(max_length=512)),
                ('time', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subname', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SoloNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('subname', models.CharField(max_length=256)),
                ('dela', models.CharField(max_length=256)),
                ('geo', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('img', models.ImageField(max_length=256, upload_to='')),
                ('head', models.CharField(max_length=256)),
            ],
        ),
    ]
