# Generated by Django 5.0.6 on 2024-05-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstop',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='solonews',
            old_name='img',
            new_name='image',
        ),
    ]
