# Generated by Django 5.0.6 on 2024-05-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_img_newstop_image_rename_img_solonews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomnews',
            name='image',
            field=models.ImageField(default='1', upload_to='images/'),
            preserve_default=False,
        ),
    ]
