# Generated by Django 5.0.6 on 2024-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_bottomnews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solonews',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
