# Generated by Django 5.0.1 on 2024-06-24 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_solonews_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
