# Generated by Django 5.0.1 on 2024-08-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='directions',
            name='subname',
            field=models.CharField(default='123', max_length=128),
            preserve_default=False,
        ),
    ]
