# Generated by Django 5.0.1 on 2024-08-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_directions_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='solonews',
            name='header_items',
            field=models.CharField(default='123', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solonews',
            name='img_items',
            field=models.ImageField(default='123', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solonews',
            name='img_mobile',
            field=models.ImageField(default='123', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solonews',
            name='name_items',
            field=models.CharField(default='123', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solonews',
            name='subname_items',
            field=models.CharField(default='123', max_length=256),
            preserve_default=False,
        ),
    ]
