# Generated by Django 5.0.1 on 2024-09-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_bottomnews_head_bottomnews_header_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='header_items',
            field=models.CharField(default='123', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='img_items',
            field=models.ImageField(default='123', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='img_mobile',
            field=models.ImageField(default='123', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='name_items',
            field=models.CharField(default='123', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='subname_items',
            field=models.CharField(default='123', max_length=256),
            preserve_default=False,
        ),
    ]
